name: bjdata
description: A BJData library for Dart.
version: 0.9.0
homepage: https://github.com/nebkat/dart-bjdata
repository: https://github.com/nebkat/dart-bjdata
issue_tracker: https://github.com/nebkat/dart-bjdata/issues
documentation: https://github.com/nebkat/dart-bjdata/blob/master/README.md
environment:
  sdk: ">=3.1.0 <4.0.0"
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
executables:
  bjdata: bjdata
